# Build the project using the Bitcraze builder docker image
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Weekly build to make sure dependencies are OK
    - cron:  '30 15 * * 0'

jobs:
  read_targets_from_file:
    uses: ./.github/workflows/read_build_targets.yml

  build:
    needs: read_targets_from_file
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ${{fromJson(needs.read_targets_from_file.outputs.platforms)}}

    env:
      PLATFORM: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Check and build
      run: docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build PLATFORM=$PLATFORM

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: ${{ matrix.platform }}-${{ github.sha }}
        path: ${{ matrix.platform }}_nrf.bin
